name: Generate Niche Pages

on:
  workflow_dispatch:
  push:
    branches: [ main ]
    paths:
      - "tools/pages.csv"
      - "tools/generate_pages.py"

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.x"

      - name: Generate pages
        run: |
          python tools/generate_pages.py

      - name: Commit & Push
        run: |
          git config user.name "github-actions"
          git config user.email "actions@github.com"
          git add -A
          if git diff --cached --quiet; then
            echo "No changes"
          else
            git commit -m "Generate niche pages from CSV"
            git push
          fi
